/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffe9d4",
        "on-surface-variant": "#000000",
        "border-subtle": "#E2E8F0",
        "on-primary-fixed-variant": "#004d62",
        "tertiary-fixed-dim": "#ffb95f",
        "on-primary-container": "#d3f1ff",
        "tertiary": "#764900",
        "primary": "#005a71",
        "primary-fixed-dim": "#81d1f0",
        "on-tertiary": "#ffffff",
        "surface-tint": "#006781",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#4fdbc8",
        "surface-container-lowest": "#ffffff",
        "background-light": "#F8FAFC",
        "surface-variant": "#e5e2e1",
        "secondary-container": "#6df5e1",
        "error": "#ba1a1a",
        "inverse-surface": "#303030",
        "surface-bright": "#fcf9f8",
        "status-warning": "#F59E0B",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#e5e2e1",
        "surface-container": "#f0eded",
        "on-background": "#1b1c1c",
        "surface-container-high": "#eae7e7",
        "tertiary-fixed": "#ffddb8",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#005048",
        "surface-container-low": "#f6f3f2",
        "background": "#fcf9f8",
        "primary-container": "#0e7490",
        "outline": "#6f787d",
        "on-error-container": "#93000a",
        "secondary-fixed": "#71f8e4",
        "surface-dark": "#0F172A",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-container": "#965f00",
        "on-primary-fixed": "#001f29",
        "inverse-primary": "#81d1f0",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-container": "#006f64",
        "on-surface": "#1b1c1c",
        "surface": "#fcf9f8",
        "error-container": "#ffdad6",
        "outline-variant": "#bec8cd",
        "on-secondary-fixed": "#00201c",
        "surface-dim": "#dcd9d9",
        "secondary": "#006b5f",
        "primary-fixed": "#b9eaff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "unit": "8px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
